Diese Testapp kann eine RuntimeExcpetion werfen, mit einer vom Nutzer eingegebenen Nachricht. Die App st√ºrzt aufgrund der Exception ab, da sie nicht abgefangen wird.
